### ISSUE TITLE
[FEED] Integration Tests Rework

### ISSUE THREAD

**Issue by robin-checkmk** [Checkmk/ansible-collection-checkmk.general#196]
**Provide your feedback**

We currently have integration tests for:
- Modules
- The server role

For the agent role it was not possible to get something up and running in a reasonable amount of time.
All of the abovementioned integration tests show some level of flakiness. This is - as far as I can tell - related to installing Checkmk into container images not made for it. More specifically, a lot of issues point towards systemd.
In my current opinion we need full-fledged VMs to properly test all aspects of the collection. Obviously this is something we have to do on our own, but which is far from trivial.

So this issue is more of a note to everyone reading this, that the integration test are not in the best shape.
We try to keep them as useful as possible, without wasting too much time.

**Component Name**

- All modules
- All roles

**Ansible Version**

```console
$ ansible --version

```

**Collection Version**

```console
$ ansible-galaxy collection list

```
**Environment**

- Local Docker
- Github Actions

**Screenshots**

**Additional context**

**Comment by robin-tribe29** [comment]
Update: Current flakiness seems to be resolved for now. It might have been an update to the Ansible Testing Containers, but I cannot tell right now.

**Comment by robin-tribe29** [comment]
Related issues for molecule tests:
- https://github.com/geerlingguy/docker-ubuntu2204-ansible/issues/6
- https://github.com/geerlingguy/docker-fedora27-ansible/issues/2

**Comment by robin-checkmk** [comment]
All flakiness is gone for some time now. So I will close this issue once #323 is merged.
