### ISSUE TITLE
[FEED] Use case: RobotMK

### ISSUE THREAD

**Issue by geof77** [Checkmk/ansible-collection-checkmk.general#250]
I'm developping a role to install RobotMK. It's in a very early stage but it might be interesting to other people.

https://github.com/geof77/ansible-robotmk

With some work, it (or parts of it) could be added to this collection, just tell me if there are useful features you would like.

Of course, suggestions and help are welcome.

Features:

* Install robotframework (pip install)
* Download and install the Robot MK .mkp
* Automatically deploy the test suites it finds in the robot directory
* Create the agent deployment rule with all the suites
* Bake the agent (deployed via automatic updates)
* Create a rule for automatic discovery of the test cases

I requires the latest version of the collection (>= 0.16.0) (uses rule module's location paramater)
Also requires ssh access to the cmk server (for stuff not supported through the API)

Related to : #215

**Comment by robin-tribe29** [comment]
Hi @geof77! I removed the `stale` label again, as I do not want this to close unnoticed.
How is your progress on this one? :)
I will have discussed internally, how we can handle this kind of related content. I sure do want to encourage endeavors like this, but want to find the right format. I will keep you posted.

**Comment by geof77** [comment]
@robin-tribe29 : thanks, my robotmk module is still actively developed, with quite a few upcoming updates.

**Comment by robin-tribe29** [comment]
I added a reference to your repository in 908bf06debc509a9fd3725c4a64be317b84666f6.
If you like it, feel free to close this issue, or provide feedback, if there is something else. :v:
