### ISSUE TITLE
[FEED] Add EL8/9 and downstream support for roles

### ISSUE THREAD

**Issue by stdevel** [Checkmk/ansible-collection-checkmk.general#349]
**Provide your feedback**

I spun up an EL9 VM (AlmaLinux 9) and by default the `server` role stops with the following error:

```command
TASK [tribe29.checkmk.server : Preflight - Fail if target host is not stable for this Role.] **************************************************************************************
fatal: [checkmk.giertz.loc]: FAILED! => {"changed": false, "msg": "This role is not stable for the target operating system, AlmaLinux 9."}
```

The workaround is to use the `--step` parameter:

```command
$ ansible-playbook -i inventory.ini checkmk.yml --step
...
Perform task: TASK: tribe29.checkmk.server : Preflight - Fail if target host is not stable for this Role. (N)o/(y)es/(c)ontinue: n

Perform task: TASK: tribe29.checkmk.server : Include OS Family specific Variables. (N)o/(y)es/(c)ontinue: c
...
```

The role works without any issues with non-RHEL downstreams (AlmaLinux, Rocky Linux) as it is literally the same distribution. Also EL9 works just fine - it should be supported as it was released more than a year ago.

**Component Name**

`server` role, but it might also apply to other roles.

**Ansible Version**

```console
$ ansible --version
ansible [core 2.14.1]
  config file = ./ansible.cfg
  configured module search path = ['/home/cstankow/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cstankow/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/cstankow/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/cstankow/.local/bin/ansible
  python version = 3.11.3 (main, May 24 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = False
```

**Collection Version**

```console
$ ansible-galaxy collection list
Collection                Version
------------------------- -------
tribe29.checkmk           0.22.0 
```

**Environment**

**Screenshots**
-

**Additional context**
-

**Comment by robin-checkmk** [comment]
Hi @stdevel and thanks for the feedback!
Also, apologies for the late answer, this one slipped.

I generally do agree with you, we can support the equivalent distributions with the role.
However, I like them to be tested at least once, and I am uncertain if we can continuously test all combinations.
Can you test the role at least for the distributions (and versions) you are using? That would give me some confidence to add the support into the role.

For testing, you can simply modify `defaults/main.yml` and add your distribution (and version) to the `checkmk_server_server_stable_os` variable. I think the format is rather obvious.

I will also look into this, when I find the time and prepare the necessary changes.
