### ISSUE TITLE
[BUG] Discovery module: sleep not in while loop

### ISSUE THREAD

**Issue by msekania** [Checkmk/ansible-collection-checkmk.general#366]
Should this line not be inside the while loop?

https://github.com/Checkmk/ansible-collection-checkmk.general/blob/d349ae8fd60e444e2aa13d8b6981b70199ab622e/plugins/modules/discovery.py#L197

**Comment by robin-checkmk** [comment]
@Max-checkmk could you take a look please? Looks valid to me.

**Comment by msekania** [comment]
@robin-checkmk, @Max-checkmk 

I have yet another comment/question, why do one creates class `servicecompletion = ServiceCompletionAPI(module)` inside the while loop (inefficient) and not outside of it?

**Comment by msekania** [comment]
Done!

BUG that treated http_code as a str # ate a lots of time. #371

unfortunately, I have also blindly trusted this part of the accepted code.

one needs a bit better test, because existing one was also passing by returning '302' in Ansible output

IMHO:
- module_utils needs a better documentation;
- and it should get also more flexible in order to cover the rest of the REST API command, otherwise it's not a help.

**Comment by Max-checkmk** [comment]
Thank You Michael for looking at this and fixing! ;)

Fixed in #369
