### ISSUE TITLE
[BUG] Discovery module: in http_code check. http_code is int and not str

### ISSUE THREAD

**Issue by msekania** [Checkmk/ansible-collection-checkmk.general#371]
`result.http_code` is `int` and not `str`

https://github.com/Checkmk/ansible-collection-checkmk.general/blob/d349ae8fd60e444e2aa13d8b6981b70199ab622e/plugins/modules/discovery.py#L193

check should be

```python
    while result.http_code == 302:
```

Ooh man, this was crazy to debug.

Anyway, fix is in #369 

may be for the future, test suite also extra checks returned codes on Anisble side.

**Comment by msekania** [comment]
Hi Max, @Max-checkmk,

It worked because `time.sleep(3)` was outside the while loop. So delay was happening always and for the single host it was enough.
One could see it on Ansible return messages. Code was 302 and not 204 as expected.

Best, Michael

**Comment by robin-checkmk** [comment]
Fixed in #369.
