### ISSUE TITLE
[FEED] provide access to recur parameter in downtime module (CEE)

### ISSUE THREAD

**Issue by nancelet** [Checkmk/ansible-collection-checkmk.general#428]
**Provide your feedback**
Provide access to `recur` parameter for downtime module (relevant only for Enterprise Edition).

**Component Name**
downtime

**Ansible Version**
```console
$ ansible --version
ansible [core 2.13.11]
  config file = None
  configured module search path = ['/home/anceletn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/anceletn/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
  jinja version = 3.1.2
  libyaml = True
```

**Collection Version**
```console
$ ansible-galaxy collection list
checkmk.general 3.0.0
```
**Environment**
Control node: Ubuntu 22.04.3 LTS
Checkmk version: 2.0.0p36 (CEE)

**Additional context**
As for now, the `recur` parameter is hard coded to `fixed` (see [plugins/modules/downtime.py:L309](https://github.com/Checkmk/ansible-collection-checkmk.general/blob/73f2475a39a511220b86a5aa1dd6ea0d709d8786/plugins/modules/downtime.py#L309))
Add possibility to provide value to this parameter in the downtime module for check_mk enterprise edition.

According to check_mk 2.0.0p36 REST API documentation:
`recur` is a string, Default: "fixed"
Enum: "fixed" "hour" "day" "week" "second_week" "fourth_week" "weekday_start" "weekday_end" "day_of_month"
Description: The recurring mode of the new downtime. Available modes are: * fixed * hour * day * week * second_week * fourth_week * weekday_start * weekday_end * day_of_month
This only works when using the Enterprise Editions. Defaults to 'fixed'.

**Comment by robin-checkmk** [comment]
From a best practice point of view, this is not desirable.
One should create rules of the type "Recurring downtimes for (hosts|services)".
So I would rather not enable this (while technically possible) option, and rather point users to the better approach.
But if demand is high, one might look into implementing this. Alternatively I would add a remark to the code, why it is hard-coded.

**Comment by nancelet** [comment]
I don't understand.
According to documentation [Regularly-scheduled downtimes](https://docs.checkmk.com/latest/en/basics_downtimes.html#scheduled) this is how we configure Regularly-scheduled downtimes.
Is there another way to do it ?

If it's configurable globally, then in our case we'll have a problem because not all hosts have the same schedule.

**Comment by robin-checkmk** [comment]
Read section 4.2. :)

It is widely considered the more elegant way.

To keep things simple: If you can implement the change: Go ahead and create a pull request. If not, we'll see if someone picks it up. It will not be a priority on our end, but someone will pick it up eventually.
