### ISSUE TITLE
[FEED] Tools for migration

### ISSUE THREAD

**Issue by muehlings** [Checkmk/ansible-collection-checkmk.general#433]
**Feedback**

I'm currently migrating from my reference sites to a fully ansible managed environment. Since I'm trying to avoid stupid things like writing dozens of rules as ansible inventory by hand, I wrote something like "site-to-ansible_inventory". It is more or less a generic tool, but each entrypoint in the API needs some adjustments (fields/params, structure for request).

If it is usefull for anybody else then me, I can publish it in my repository and link it here. If you are interested, leave a comment below.

**Component Name**

None

**Screenshots**

Currently active tag_group written as ansible variable, which I'm looping over in my playbook:
![grafik](https://github.com/Checkmk/ansible-collection-checkmk.general/assets/80385927/d6885df9-9dc6-42bc-b5c5-c13351e0f052)

Example of a generic playbook:
![grafik](https://github.com/Checkmk/ansible-collection-checkmk.general/assets/80385927/4ccaf251-4a26-4e92-aef9-1cbdcbaf0967)

**Comment by robin-checkmk** [comment]
I cannot estimate the value for the wider community, but we do include these kinds of things in https://github.com/Checkmk/ansible-collection-checkmk.general/blob/main/COMMUNITY.md. So if you want to publish it, we will gladly include it there. :v:

**Comment by muehlings** [comment]
I have created a repository for my additional stuff under https://github.com/muehlings/ansible-collection-checkmk.helper

Feel free to link it in COMMUNITY.md.
