### ISSUE TITLE
[BUG] Deleting a downtime fails, due to missing `site_id` in API call

### ISSUE THREAD

**Issue by robin-checkmk** [Checkmk/ansible-collection-checkmk.general#438]
**Describe the bug**

When deleting a downtime, we receive the following error:
```
"msg": "Error calling API while removing downtime from 'test5.tld' with comment 'Created by Ansible'. HTTP code 400. Details: b'{\"title\": \"Bad Request\", \"status\": 400, \"detail\": \"These fields have problems: site_id\", \"fields\": {\"site_id\": [\"Missing data for required field.\"]}}', "
```
As far as I could read the code of the `downtime` module, we nowhere pass the site_id to the API call to delete the downtime. This is necessary since [Werk 15966](https://checkmk.com/werk/15966).
This only affects 2.2.0p8 and above. Versions below are not impacted. So we need to make sure the fix does not break compatibility with older versions.

**Component Name**

Component Name: downtime

**Ansible Version**

```console
$ ansible --version
N/A
```

**Checkmk Version and Edition**

```console
CRE 2.2.0p8
```

**Collection Version**

```console
$ ansible-galaxy collection list
N/A
```

**To Reproduce**
1. Try to delete a 
2. Run '....'
3. Execute '....'

**Expected behavior**

Downtime is deleted.

**Actual behavior**

The module fails.

**Minimum reproduction example**

```yaml

```

**Additional context**

See the failing workflow run: https://github.com/Checkmk/ansible-collection-checkmk.general/actions/runs/6061520200

**Comment by lgetwan** [comment]
I discussed this with the REST API developers. They will make the site_id only mandatory when using _delete_type=by_id_. We're using the type _query_.
Thus, we have to wait until it's fixed upstream.

**Comment by lgetwan** [comment]
This has been fixed upstream with the Werk https://checkmk.com/werk/16156 for Checkmk versions 2.2.0p13 and 2.3.0b1.

**Comment by robin-checkmk** [comment]
Currently all tests are looking good with current Checkmk versions, so we will close this issue as resolved.
If this issue arises again, please open a new issue and reference this one. Thanks!
