### ISSUE TITLE
[BUG] Agent & Updater registration in distributed environment does not work

### ISSUE THREAD

**Issue by AngelNev** [Checkmk/ansible-collection-checkmk.general#442]
Verify first that your issue is not already reported [here](https://github.com/Checkmk/ansible-collection-checkmk.general/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
Where possible also test if the latest release and main branch are affected too.
Complete all sections as described!

**Describe the bug**
Till now I used a "simple" powershell script to install the agent, register for tls and register for updates in a distributed environment.

The agent updater registration is "dynamic", I don't need to omit the param.. like this:
& 'C:\Program Files (x86)\checkmk\service\check_mk_agent.exe' updater register -H $HostFqdn -p https -U $Username -P $Password -v 

For the tls registration, I have to do against the slave host, like this:
& 'C:\Program Files (x86)\checkmk\service\cmk-agent-ctl.exe' register --server slave-host.fqdn --site Slave --hostname $HostFqdn --user $Username --password $Password --trust-cert

**Component Name**
Component Name: checkmk.general.agent

**Ansible Version**
```console
$ ansible --version
2.14.2
```

**Checkmk Version and Edition**

```console
Checkmk Enterprise Edition 2.2.0p9
```

**Collection Version**

```console
$ ansible-galaxy collection list
checkmk.general:3.2.0
```

**Expected behavior**
I think my problem would be, when there are more variable to use for the agent installation:

{{ checkmk_agent_registration_server }} > for the tls registration
{{ checkmk_agent_updater_registration_server }} > new var for the updater registration

Extend the actual play with the new variables.

**Actual behavior**
I can't use the agent role for my windows systems in the actual distributed environment.
When I set the vars checkmk_agent_registration_server to the main site, the updater registration does not work. When I try the other way around, the agent registrations fails.

**Comment by robin-checkmk** [comment]
You have to do both registrations against the site the host is monitored on. TLS will exclusively work with the site the host is monitored on, the updater could be registered against the site the host is monitored on and against the central site. But I see no use case for the latter one, and I do not want to clutter the role with unnecessary variables.

Maybe you can clarify your use case further, so I can get a better feeling of how it looks like exactly. Thanks!
