### ISSUE TITLE
[BUG] The tag `install-package` in the server role does not install the package

### ISSUE THREAD

**Issue by hb9hnt** [Checkmk/ansible-collection-checkmk.general#449]
Hey Robin

I noticed another minor problem: I you try to only install the package using the `install-package` tag, the package is not installed because the `include_tasks` call isn't tagged. The following diff fixes the problem:

```diff
--- tasks/main.yml.orig 2023-10-11 12:29:23.722053365 +0200
+++ tasks/main.yml      2023-10-11 12:30:00.740420464 +0200
@@ -86,6 +86,8 @@
 
 - name: Include OS Family specific Playbook.
   ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
+  tags:
+    - install-package
 
 - name: Include Site Management Playbook.
   ansible.builtin.include_tasks: "sites.yml
```

Additionally I noticed that the tags `install-package` depends on `include-os-family-vars` and cannot be used alone. I'm not sure whether this is done on purpose.

**Comment by robin-checkmk** [comment]
To be honest, the tagging was done once by a contributor and never really followed through.
I am to this day not a big fan of it. In the role, there are several tasks now, which are untagged.
That can be okay, but would need review, and I am uncertain, if I want to invest the time to go through every single task.

As tags have no dependencies, one would need to tag tasks in a way that compensates for this.

I implemented your suggested fix, but if you rely on tagging, maybe you can review the current state and prepare a PR for it.

**Comment by hb9hnt** [comment]
Thanks @robin-checkmk - I don't heavily rely on tags, I just tried to used them because they were documented. My usecase was to install a new version of Checkmk without updating the sites and then update the sites manually, in case I have to merge any config. However, this could be achieved with separate version variables, too. Currently I use one global checkmk-version variable.

So, for now I think I'm finde with the current state of things. So as far as I'm concerned we can close this issue.

**Comment by robin-checkmk** [comment]
Okay then, I pushed a fix for your immediate finding, that will be released with the next collection version.
Thanks for reporting!
