### ISSUE TITLE
[BUG] Unable to install version 3.3.0 of this collection

### ISSUE THREAD

**Issue by mueller-ma** [Checkmk/ansible-collection-checkmk.general#466]
**Describe the bug**
Version 3.3.0 isn't uploaded to Galaxy, so it cannot be installed.

````
$ ansible-galaxy collection install --force checkmk.general:==3.2.0 # works
$ ansible-galaxy collection install --force checkmk.general:==3.3.0
Starting galaxy collection install process
Process install dependency map
ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* checkmk.general:==3.3.0 (direct request)
````
In the version dropdown menu on https://galaxy.ansible.com/ui/repo/published/checkmk/general/ the latest version is 3.2.0.

**Ansible Version**

```console
$ ansible --version
ansible [core 2.15.5]
```

**Comment by robin-checkmk** [comment]
Please keep an eye on this post: https://forum.checkmk.com/t/checkmk-goes-ansible/25428/53?u=robin.gierse

**Comment by robin-checkmk** [comment]
The issue was just fixed. :tada: 
Have fun with `3.3.0`. :robot:
