### ISSUE TITLE
[FEED] Agent plugin provisioning

### ISSUE THREAD

**Issue by ivomarino** [Checkmk/ansible-collection-checkmk.general#473]
Just a small question, I saw that in the legacy ansible code there was support for [rolling out plugins directly to agents](https://github.com/Checkmk/ansible-checkmk/blob/master/README_cmk_host_plugins.md), is this in some way also achievable in `ansible-collection-checkmk.general`? Thanks for any feedback

**Comment by robin-checkmk** [comment]
Hi @ivomarino and thanks for asking!
While the feature you mention would definitely be nice to have, we currently have no focus on it.
For commercial users, there is the [Checkmk Agent Bakery](https://docs.checkmk.com/latest/en/wato_monitoringagents.html#bakery) that does exactly this. Obviously that does not help the open source users.

So the bottom line here is: We do appreciate pull requests that implement (parts of) this functionality, but there are no plans driven by us to implement this. So feel free to get started working on this, we do appreciate every contribution!

**Comment by ivomarino** [comment]
Hi @robin-checkmk and thanks for your answer, I wrote a little bit of ansible code to achieve this:

from `ansible.cfg`:
```
[privilege_escalation]
become_flags="--preserve-env=SSH_AUTH_SOCK"

[ssh_connection]
ssh_extra_args = -o ForwardAgent=yes
```

from `host_vars/debian-01.yaml`:
```
conf_shell_default:
  - { cmd: 'scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /opt/omd/versions/{{ checkmk_agent_version }}.{{ checkmk_agent_edition }}/share/check_mk/agents/plugins/mk_apt root@{{ inventory_hostname }}:/usr/lib/check_mk_agent/plugins/mk_apt', delegate_to: 'monitoring-node' }
conf_shell: "{{ conf_shell_default|default([]) + conf_shell_custom|default([]) }}"
```

from `playbook.yml`:
```
post_tasks:
    - name: shell
      ansible.builtin.shell: '{{ item.cmd|default("") }}'
      args: '{{ item.args|default({}) }}'
      delegate_to: '{{ item.delegate_to|default("") }}'
      loop: '{{ conf_shell|default([]) }}'
      tags: [ 'post', 'shell' ]
```

which results in:
```
...
TASK [shell] *********************************************************************************************************************************************************************************************************************************
changed: [debian-01-> monitoring-node] => (item={'cmd': 'scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /opt/omd/versions/2.1.0p36.cre/share/check_mk/agents/plugins/mk_apt root@debian-01:/usr/lib/check_mk_agent/plugins/mk_apt', 'delegate_to': 'monitoring-node'})
...
```

when executed with `-o '--limit debian-01 --tags shell'`. Maybe it's useful. Other ways of copying files over can be found [here](https://stackoverflow.com/a/49731914) also.

**Comment by ivomarino** [comment]
another option would be of course to download the plugin, like:
```
conf_shell_custom:
  - { cmd: 'fetch -o /usr/lib/check_mk_agent/plugins/mk_postgres.py https://github.com/Checkmk/checkmk/blob/v2.1.0p22/agents/plugins/mk_postgres.py && chmod +x /usr/lib/check_mk_agent/plugins/mk_postgres.py', args: { creates: '/usr/lib/check_mk_agent/plugins/mk_postgres.py' } }
conf_shell: "{{ conf_shell_default|default([]) + conf_shell_custom|default([]) }}"
```

**Comment by robin-checkmk** [comment]
This approach sounds very weird to me, to be blunt.

Why not [fetch](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fetch_module.html#ansible-collections-ansible-builtin-fetch-module) the plugins from the Checkmk site and [copy](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html#ansible-collections-ansible-builtin-copy-module) them to the target hosts using the appropriate modules?

**Comment by ivomarino** [comment]
> This approach sounds very weird to me, to be blunt.
> 
> Why not [fetch](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fetch_module.html#ansible-collections-ansible-builtin-fetch-module) the plugins from the Checkmk site and [copy](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html#ansible-collections-ansible-builtin-copy-module) them to the target hosts using the appropriate modules?

Yes of course, would work the same way, same concept
