### ISSUE TITLE
[FEED]: virt1 support

### ISSUE THREAD

**Issue by muehlings** [Checkmk/ansible-collection-checkmk.general#477]
**Provide your feedback**
Any chances for the **server role** to handle the virt1 appliance?

**Component Name**
Component Name: roles/server

**Comment by robin-checkmk** [comment]
Hi @muehlings!
I can say with certainty, that we will not support the Checkmk Appliance, be it the virtual or physical ones in the foreseeable future.
The main reason is, that it is an appliance and it works differently than your average Linux. So we would need an API on the appliance to manage it in a way, that is compliant with it being an appliance. As there is no such API and there are no plans to implement one, we cannot support the appliance with this collection.

P.S.: I am aware, that technically there might be ways to manage the appliance through Ansible. But we do *not* encourage those yet.

**Comment by robin-checkmk** [comment]
Actually it is not, there is more going on underneath.
If you try to install Checkmk through APT in the appliance, you are going to have a bad time.
