### ISSUE TITLE
[BUG] 'checkmk_agent_protocol' is undefined

### ISSUE THREAD

**Issue by mueller-ma** [Checkmk/ansible-collection-checkmk.general#488]
**Describe the bug**

I updated the collection to 4.0 and renamed some defined variables. Rolling it out to one client crashes the role.

You renamed `checkmk_agent_protocol` to `checkmk_agent_server_protocol` (https://github.com/Checkmk/ansible-collection-checkmk.general/commit/77d68179dbbfe1bbd4c4599eb4425052cc7b873a#diff-de8812fff1ae18448b386c4840151ea0ba822193cf2a8d574c5753c212ce9299R36), but missed two places: https://github.com/search?q=repo%3ACheckmk%2Fansible-collection-checkmk.general%20checkmk_agent_protocol%20&type=code

**Collection Version**

```console
$ ansible-galaxy collection list
4.0
```

**Comment by robin-checkmk** [comment]
Thanks for reporting this!
Another example of "No matter how careful you are and test, something always slips though.
I will prepare a fix and release it within a day.
