### ISSUE TITLE
[BUG]  Failed to create piggyback_translation rule with regular expressions translation

### ISSUE THREAD

**Issue by fabriceverkor** [Checkmk/ansible-collection-checkmk.general#499]
**Describe the bug**
A piggyback_translation rule created by Ansible gives "Unable to read current options of this rule. Falling back to default values. When saving this rule now, your previous settings will be overwritten. Problem was: Multiple regular expressions: The datatype must be a tuple, but is list." in GUI
The rule is not working.

**Component Name**: rule

**Ansible Version**
ansible [core 2.12.10]
config file = /etc/ansible/ansible.cfg
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3/dist-packages/ansible
ansible collection location = /etc/ansible/collections
executable location = /usr/bin/ansible
python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
jinja version = 2.11.3
libyaml = True

**Checkmk Version and Edition**
2.2.0p14 Raw

**Collection Version**
ansible.netcommon 3.1.1
ansible.posix 1.5.2
ansible.utils 2.6.1
ansible.windows 1.7.3
azure.azcollection 1.16.0
checkmk.general 4.0.1
community.general 5.7.0
community.grafana 1.5.2
community.postgresql 2.2.0
community.windows 1.7.0
fahcsim.grafana_stack 1.2.1
fortinet.fortios 2.1.2
nutanix.ncp 1.8.0
veeamhub.veeam 1.3.

**To Reproduce**
1- create a rule with ansible-playbook rule.yml
2- create the same rule by GUI

**Expected behavior**
The same behaviour than for a rule created by GUI

**Actual behavior**
- The rule is created without error by Ansible
- In GUI, in the list of "Hostname translation for piggybacked host" rules, I can see the same regular expressions translation than when a same rule is created :
Multiple regular expressions: (.+), hb-dev_\1
- But I go in rule itself, the regular expression is not visible and the following error message is printed :
Unable to read current options of this rule. Falling back to default values. When saving this rule now, your previous settings will be overwritten. Problem was: Multiple regular expressions: The datatype must be a tuple, but is list.
- in the corresponding rule.mkfile, I can't see any difference, see below :
{'id': '37f13f59-9528-4ea1-8fad-8d488fa80627', 'value': {'regex': [('(.+)', 'hb-dev_\\1')]}, 'condition': {'host_name': ['hb-dev.inf.mfg.vic.verkor.com']}, 'options': {'disabled': False, 'description': 'Docker Containers on hb-dev'}},
{'id': '44fee3ea-e3f6-42f4-afb5-0a69a97ab5eb', 'value': {'regex': [['(.+)', 'hb-dev_\\1']]}, 'condition': {'host_name': ['hb-dev.inf.mfg.vic.verkor.com']}, 'options': {'disabled': False, 'description': 'Docker Containers on hb-dev'}},

**Minimum reproduction example**

- name: Create Rule to prefix container ID in piggyback
  checkmk.general.rule:
    server_url: "{{ checkmk_url }}"
    site: "{{ site }}"
    automation_user: automation
    automation_secret: "{{ VAULT_CHECKMK_AUTOMATION_SECRET }}"
    ruleset: "piggyback_translation"
    rule:
      properties:
        description: "Docker Containers on {{ hostname }}"
      conditions:
        host_name:
          match_on:
            - "{{ fqdn }}"
          operator: one_of
      value_raw: "{'regex': [('(.+)', '{{ hostname }}_\\\\1')]}"

**Comment by robin-checkmk** [comment]
I am fairly certain, that this is related to #186.

You probably want to check the `value_raw` and make sure Ansible does not change it, compared to the exported value from the UI. Currently, Ansible (or Jinja2 and YAML respectively) might change the string and then the result received by Checkmk does not work anymore.

**Comment by fabriceverkor** [comment]
Thx for your answer.
That is what I did by checking the generated file rule.mk on CheckMK server it self.
I can see both rules, see below. Except the rule ID, there is no difference (verified by saving them in seperated files and testing them with cksum and vimdiff).
So Ansible did not changed something, right ?
Or should I look somewhere else on CheckMK server ?

{'id': '37f13f59-9528-4ea1-8fad-8d488fa80627', 'value': {'regex': [('(.+)', 'hb-dev_\1')]}, 'condition': {'host_name': ['hb-dev.inf.mfg.vic.verkor.com']}, 'options': {'disabled': False, 'description': 'Docker Containers on hb-dev'}},
{'id': '44fee3ea-e3f6-42f4-afb5-0a69a97ab5eb', 'value': {'regex': [['(.+)', 'hb-dev_\1']]}, 'condition': {'host_name': ['hb-dev.inf.mfg.vic.verkor.com']}, 'options': {'disabled': False, 'description': 'Docker Containers on hb-dev'}},

**Comment by fabriceverkor** [comment]
My bad : there is a difference !!
The good rule manually created :  'value': {'regex': [('(.+)', 'hb-dev_\1')]}
The bad rule created by Ansible : 'value': {'regex': [['(.+)', 'hb-dev_\1']]}
So you are right : Ansible the provided raw_value "{'regex': [('(.+)', '{{ hostname }}_\\1')]}

**Comment by robin-checkmk** [comment]
And that is the very issue, that was discussed in the linked issue. :+1: 

With Checkmk 2.3 there should be changes to the REST API, which might enable us to improve the situation and properly handle data conversion. But that is all tentative, and we cannot promise anything at this point.

**Comment by fabriceverkor** [comment]
Indeed, it is working fine when  hostname is hard-coded like : "{'regex': [('(.+)', 'hb-dev_\1')]}
I tried to go through intermediate file containing the string above.
But when I try to get the content of file as a variable, it is interpreted as a dict. I'm in a infinite loop.

**Comment by fabriceverkor** [comment]
In waiting, I found an ugly way with Ansible tasks to fix rule in rules.mk file directly on CheckMK server. Now the rule is OK in CheckMK GUI
But it's still duplicated on each run. As in my case, the unicity field is the rule name, I just have to add tasks to list existing rules and prevent rule creation above if already in the list.
I know that it's not a pretty way but I need to go further.

**Comment by robin-checkmk** [comment]
Actually, I know of a customer, who is going the same way. I need to discuss this internally, as I think we can improve things on the Checkmk site of things. But that is not a short term solution.

**Comment by robin-checkmk** [comment]
@fabriceverkor I know that it has been some time and I come back bearing bad news: The plans to improve the output data format of the REST API have been de-prioritized, meaning they will not make it into Checkmk 2.3. This in turn means, that there will be no significant improvement this year. As I want to avoid zombie issues, I will close this issue for now.
But rest assured, we are aware of this situation and it still on our agenda.
