### ISSUE TITLE
[BUG] check-mode fails for cmk_server role

### ISSUE THREAD

**Issue by sdx23** [Checkmk/ansible-collection-checkmk.general#505]
**Describe the bug**
Calling a playbook using the cmk_server role in check mode (--check) fails with message

    fatal: [server]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stderr_lines'\n\nThe error appears to be in '.ansible/collections/ansible_collections/checkmk/general/roles/server/tasks/main.yml': line 75, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: \"Print Verification Output.\"\n      ^ here\n"}

This is due to a missing check regarding check-mode, such as when: not ansible_check_mode`. Example fix:

    - name: "Print Verification Output."
      ansible.builtin.debug:
        msg: "{{ checkmk_server_verify_state.stderr_lines }}"
      when: not ansible_check_mode

(besides: it is dubious whether this print is actually necessary)

**Component Name**

Component Name: server role

**Ansible Version**

    $ ansible --version
    ansible 2.10.8
    config file = ./ansible.cfg
    configured module search path = ['./.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    ansible python module location = /usr/lib/python3/dist-packages/ansible
    executable location = /usr/bin/ansible
    python version = 3.7.3 (default, Oct 11 2023, 09:51:27) [GCC 8.3.0]

**Checkmk Version and Edition**

```console
2.2.0p16 (CRE)
```

**Collection Version**

```console
$ ansible-galaxy collection list
…
checkmk.general    4.0.0

```

**To Reproduce**

Run a playbook using the checkmk_server role to setup a checkmk site in check mode (--check).

**Expected behavior**
Playbook running and possibly reporting changed tasks.

**Actual behavior**
Playbook aborts.

**Comment by robin-checkmk** [comment]
This situation is way bigger than just one or two tasks.
There are many tasks today, that cannot work in check mode.
For example: To install the Checkmk server, one needs to download the package. You would not want that in check mode, but how would you check the installation then?
Also, a major thing is that we interact with `omd` commands directly, there is no module for that (yet).
All in all: Check mode might be nice, but it is not trivial to get there and for now, and we cannot focus working on it.
If you want to contribute something that works toward that goal, it will be highly appreciated!
But for now, I will close this issue as not planned, as it is the current state and will not change in the foreseeable future.
