### ISSUE TITLE
[BUG] Investigate behavior of the parent attribute when passed to the `host` or `folder` module

### ISSUE THREAD

**Issue by robin-checkmk** [Checkmk/ansible-collection-checkmk.general#515]
**Describe the bug**

When passing the parent `parent` attribute to the `host` or `folder` module one has to use a very particular syntax:
```YAML
parents: ["my_parent_host"]
```
If we do not pass it as a list, but a string for example, the modules do odd things, like interpreting every character as a dedicated host.

**Component Name**

Component Name: host, folder

**Ansible Version**

```console
$ ansible --version

```

**Checkmk Version and Edition**

```console
2.2.0p17 (CRE)
```

**Collection Version**

```console
$ ansible-galaxy collection list
`4.1.0`
```

**To Reproduce**
Steps to reproduce the behavior: See above.

**Expected behavior**

The modules are more robust towards the data type.
Or they would refuse to use "false" values and print an error.

**Actual behavior**

See above.

**Minimum reproduction example**

```yaml

```

**Additional context**

**Comment by msekania** [comment]
@robin-checkmk, 

This is quite normal behavior for other Ansible modules too, which wait for a list but receive a string.

If I am not mistaken, the package module handles both inputs adequately.
One can implement the similar semantic here too, but I'm not sure if it's worth it.

**Comment by robin-checkmk** [comment]
Thanks for your input @msekania!

I do agree, that technically this is fine, but is quite inconvenient for a user.
If it is not too much effort, I think implementing this for convenience would be great.
But we do not want to invest too much time probably.

**Comment by msekania** [comment]
Hi @robin-checkmk,

several points:
- why it's marked like bug, when it is not?
- It also states `parents`, plural, so one could guess that list is what is expected.
- I have an idea (have not tested though) how one can include the desired conversion in the corresponding modules when attribute contain `parents`, but what's about similar attributes then?

**Comment by robin-checkmk** [comment]
Hi @msekania,

1. While I see your point, I think to a user it sure feels like a bug.
2. That comes down to the fact that the REST API uses the plural, although in many use cases, there is only a single parent. But that is not really the point of this issue.
3. I see your point and I do realize that it is just one among a lot of possible attributes. I need to look for another example, but I have none in mind right now. However, the parent attribute is validated in the UI and you can only add existing hosts as parents. This is currently broken for the REST API, but once that is fixed, we will get errors directly instead of having non-existing parents configured.

I think this is more of a data type issue, than anything else. We should probably start by searching for attributes, which are can be both a list of one or a list of many. Once we understand if the behavior is the same for several attributes, we can start thinking about a proper solution. And I do understand, that the behavior makes sense. I just see the current state as inconvenient at best for the average user, which is why I want to improve things.

**Comment by msekania** [comment]
Hi @robin-checkmk,

I see you point.

Indeed it will be great to have in general parsers for standardized parameter sets e.g., FolderUpdateAttributes, CustomHostAttributes, ...

Parameter definitions  that go differ than `raw` will be also good, there was also one PR in preparation by @geof77 which is gone. That is one way to go before taking the parsing of standardized parameters in general modules. Question remains though. How stable are those parameter definitions from version to version?

Anyway, I know how to stabilize `parents` behavior.
Currently there are two PR on folder module and I am not sure whether @lgetwan has similar modernization for host module.
I'll make a PR with implementation afterward then.

**Comment by msekania** [comment]
Hi @robin-checkmk,

It might take longer with folder module, so one can go ahead and merge the following #545 fix before.

**Comment by msekania** [comment]
@robin-checkmk,

there is yet another parameter with similar issues,
`nodes`
for cluster in host.

**Comment by robin-checkmk** [comment]
> there is yet another parameter with similar issues,
> nodes
> for cluster in host.

@msekania sorry for the late response. Can you implement the changes you made in #545 for this issue as well?

**Comment by msekania** [comment]
@robin-checkmk,

that will be relevant with cluster functionality, which is in preparation. I am just waiting for folder and host related PR-s to be merged, not to mix up everything.

**Comment by robin-checkmk** [comment]
Understood, great news! And I agree, we need to clean some things up before moving forward.
We have quite some things going on right now, so we appreciate your patience very much!
