### ISSUE TITLE
[FEED] Enable managing cluster objects with the `host` module

### ISSUE THREAD

**Issue by robin-checkmk** [Checkmk/ansible-collection-checkmk.general#518]
**Provide your feedback**

It should be possible to configure cluster objects in Checkmk, either through the `host` module, or through a dedicated module.

**Component Name**

Component Name: host

**Ansible Version**

```console
$ ansible --version

```

**Collection Version**

```console
$ ansible-galaxy collection list

```
**Environment**

**Screenshots**

**Additional context**

There was a PR once, but the contributor did not follow through: #246

**Comment by msekania** [comment]
@robin-checkmk,

in coming weeks I'll have time for it.
I will need this part of the functionality for myself in the future, so I can see if I can implement it right away.

**Comment by robin-checkmk** [comment]
Implemented in #562.

**Comment by msekania** [comment]
Hi @robin-checkmk,

Not yet, it will come with the next version not with the 4.4.0

> Implemented in #562.

**Comment by robin-checkmk** [comment]
I was lazy and closed the issue "early" in a sense. I felt like that is okay, as I reported it. :grimacing: 
But the work is done, I just need to find time to finalize the release.
