### ISSUE TITLE
[FEED] Find a better name for `pager_address` of the `user` module

### ISSUE THREAD

**Issue by robin-checkmk** [Checkmk/ansible-collection-checkmk.general#519]
**Provide your feedback**

The module option `pager_address` of the `user` module feels odd. I think just `pager` would suffice, or maybe `pager_number`. But the `address` bit only works with email, I guess, but the corresponding option is just named `email`.

**Component Name**

Component Name: user

**Ansible Version**

```console
$ ansible --version

```

**Collection Version**

```console
$ ansible-galaxy collection list

```
**Environment**

**Screenshots**

**Additional context**

**Comment by lgetwan** [comment]
Thanks to @Max-checkmk, this issue is solved in #299.
