### ISSUE TITLE
[FEED]Agent download fails in distributed setup

### ISSUE THREAD

**Issue by HaZet1968** [Checkmk/ansible-collection-checkmk.general#532]
Please verify first that your feedback is not already reported [here](https://github.com/Checkmk/ansible-collection-checkmk.general/issues?q=is%3Aissue+sort%3Aupdated-desc).
If possible and useful provide additional information below. This is optional however.

**Provide your feedback**
As mentioned here https://forum.checkmk.com/t/agent-download-fails-in-distributed-setup/36610/3 Agent download fails in distributed setups.
Unfortunatly I have to work in an closed environment so i cannot make a pull request. Instead I added my changes in the attached main.txt (must be renamed to main.yml, see below). Maybe someone can make a pull request out of it.

**Component Name**

Component Name: Agent download
I added three new configuration variables:
checkmk_agent_download_server_protocol
checkmk_agent_download_server
checkmk_agent_download_site

I changed checkmk/general/roles/agent/vars/main.yml to the following (see attachment)
[main.txt](https://github.com/Checkmk/ansible-collection-checkmk.general/files/14035038/main.txt)
 works for me

**Ansible Version**

```console
$ ansible --version
2.12.10
```

**Collection Version**

```console
$ ansible-galaxy collection list
4.1.0
```
**Environment**

checkmk 2.2.0p18

**Screenshots**

**Additional context**

**Comment by robin-checkmk** [comment]
Hi @HaZet1968 and thanks for your contribution!
Just making sure, I understand your proposal correctly: You want to add the new variables to be able to set a server different from `checkmk_agent_server` and `checkmk_agent_registration_server`, right?

**Comment by torbenubechel** [comment]
Hi at all,

we facing a similar issue.

Distributed setup, where the distrubuted site are only read-only.

So the agent role have to 
- create the new host at the master server with site-tag for the distributed site
- register TLS at the distributed server with the distributed site
- register updader at the distributed server with the distributed site

At the moment step 2 fails, as it tries to register at the master server (checkmk_agent_server) which does not react for the distrbuted site.

How can we assist to bring the differentiation into the code.

**Comment by robin-checkmk** [comment]
@torbenubechel thanks for chiming in here. My question towards the original reporter of this was targeted at confirming whether the role can already do, what they need.

In your case, I would assume, setting the following two variables to the remote site, instead using the default (which is the central site), should resolve your situation.

```yaml
checkmk_agent_registration_server: "{{ checkmk_agent_server }}"
checkmk_agent_registration_site: "{{ checkmk_agent_site }}"
```

**Comment by torbenubechel** [comment]
> @torbenubechel thanks for chiming in here. My question towards the original reporter of this was targeted at confirming whether the role can already do, what they need.
> 
> In your case, I would assume, setting the following two variables to the remote server and site, instead using the default (which is the central site and server), should resolve your situation.
> 
> ```yaml
> checkmk_agent_registration_server: "{{ checkmk_agent_server }}"
> checkmk_agent_registration_site: "{{ checkmk_agent_site }}"
> ```

@robin-checkmk you were right.
My mistake was the wrong registration site.

Now its working!

Thanks a lot!

**Comment by robin-checkmk** [comment]
Closing this, as the original poster never came back and the intermittent issue was resolved already.
