### ISSUE TITLE
host_tag_group Endpoint changed the parameters id/ident

### ISSUE THREAD

**Issue by lgetwan** [Checkmk/ansible-collection-checkmk.general#547]
**For our Awareness**

[Werk 16364](https://checkmk.com/werk/16364) unifies the parameters of the host tag group endpoints

**Component Name**

Module tag_group

**Checkmk Version and Edition**

Checkmk < 2.2.0p??: There's a mixed usage of "id" and "ident"
2.2.0p?? < Checkmk < 2.4.0b1 : API always accepts both, "id" and "ident"
Checkmk > 2.4.0b1: Only "id" is accepted.

**Expected behavior**

No matter what Checkmk version the module contacts, it should always use the right parameter name.

**Actual behavior**

The current module version will stop working with Checkmk >= 2.4.0b1

**Comment by robin-checkmk** [comment]
Implemented in #640.
