### ISSUE TITLE
[BUG] Agent role has unecessary changes, when the agent is already registered and added to CheckMK

### ISSUE THREAD

**Issue by peterge1998** [Checkmk/ansible-collection-checkmk.general#554]
**Describe the bug**

When I run with these variables, to ensure that the host gets added to the monitoring and is registered, I receive 5 changes every time the role is being executed:
```
checkmk_agent_discover: 'true'
checkmk_agent_tls: 'true'
checkmk_agent_auto_activate: 'true'
```

**Component Name**

Component Name: download, registration & activation

**Ansible Version**

```console
$ ansible --version
ansible [core 2.16.2]
```

**Checkmk Version and Edition**

```console
2.2.0p21 (CRE)
```

**Collection Version**

```console
# /home/peterge/.ansible/collections/ansible_collections
Collection                               Version
---------------------------------------- -------
ansible.posix                            1.5.4  
checkmk.general                          4.2.0  
community.docker                         3.7.0  
community.general                        8.3.0  
community.library_inventory_filtering_v1 1.0.0
```

**To Reproduce**
1. Run agent role on a host that has already been registered and added to CheckMK

**Expected behavior**
I would expect no changes in the play when the host has already been added.

**Actual behavior**
There are 5 changes, which are unecessary IMHO. [no_changed_when](https://ansible.readthedocs.io/projects/lint/rules/no-changed-when/) should be added to them. These are the 5 changes that I mean:

TASK [checkmk.general.agent : Linux: Download Vanilla CRE agent.] **************
changed: [midevansible.company.lan]

TASK [checkmk.general.agent : Linux: Register Agent for TLS.] ******************
changed: [midevansible.company.lan]

TASK [checkmk.general.agent : Fetch fresh monitoring data from host.] **********
changed: [midevansible.company.lan -> localhost]

TASK [checkmk.general.agent : Update monitored services and labels on host.] ***
changed: [midevansible.company.lan -> localhost]

RUNNING HANDLER [checkmk.general.agent : Activate Changes.] ********************
changed: [midevansible.company.lan -> localhost]

**Minimum reproduction example**

```yaml
- hosts: midevansible.company.lan
  roles:
     - checkmk.general.agent
```

**Additional context**

These 5 changes I mentioned should not show up as changes, they should be treated as OK when already done and not modified by this execution.
The reason why I need this, is because I am executing ansible in an CI Pipeline and I want to be able to see correct information in the play recap.

Greetings, @robin-checkmk btw :)

**Comment by robin-checkmk** [comment]
Moinsen Peter! :slightly_smiling_face: 

Thanks for reporting this. Let me provide some background.

> TASK [checkmk.general.agent : Linux: Download Vanilla CRE agent.] **************
> changed: [midevansible.company.lan]

At the time of the download, we do not know whether we actually need the file. As the download goes to `/tmp` by default, the file will be gone after a reboot. Hence, it gets downloaded after every reboot. If you run the task twice without rebooting, you will see, that the second run yields no change.
 
> TASK [checkmk.general.agent : Linux: Register Agent for TLS.] ******************
> changed: [midevansible.company.lan]

This is a `ansible.builtin.command` task, which makes it non-trivial to make it idempotent. From the top of mind I am uncertain, if we can use the command output or not. This requires further investigation.

> TASK [checkmk.general.agent : Fetch fresh monitoring data from host.] **********
> changed: [midevansible.company.lan -> localhost]

This task actually triggers a re-scan of the host, which means, the "changed" state is technically right (which is the best kind of being right :wink:)

> TASK [checkmk.general.agent : Update monitored services and labels on host.] ***
> changed: [midevansible.company.lan -> localhost]

This one might be valid as well. Unless something actually changes. But if you are certain this is not okay, it is probably an issue with the `discovery` module and not with the agent role. I would ask you double-check, if you can reproduce the issue with a dedicated task using the `discovery` module and if so, open a dedicated issue for the module.

> RUNNING HANDLER [checkmk.general.agent : Activate Changes.] ********************
> changed: [midevansible.company.lan -> localhost]

Are you sure there are no changes to activate? This one is the same as the last one. If the change detection does not work, it is a problem with the module, and we need a dedicated issue for the `activation` module.

**Comment by peterge1998** [comment]
Of course I get why the first 3 are showing up as change. But in my opinion it makes way more sense to use `changed_when: false` here, otherwise my play recap is filled up with irrelevant changes (like downloading to tmp or rescanning).

I do not find any way to mute the changes for a role execution. So I guess I have to live with those changed tasks :(

**Comment by peterge1998** [comment]
not planned

**Comment by peterge1998** [comment]
not planned

**Comment by peterge1998** [comment]
not planned
