### ISSUE TITLE
[Feature Request] Create Host and Service Groups Rules via Ansible

### ISSUE THREAD

**Issue by atanaskupenov** [Checkmk/ansible-collection-checkmk.general#555]
Verify first that your issue is not already reported [here](https://github.com/Checkmk/ansible-collection-checkmk.general/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
Where possible also test if the latest release and main branch are affected too.
Complete all sections as described!

**Describe the bug**

It would be really useful to have a way of creating Host/Service Group rules via Ansible that will allow you to map Host Groups to Tags or Folders.
**Component Name**
Host/Service Groups

Component Name: Host/Service Groups

**Ansible Version**

```console
$ ansible --version
ansible [core 2.16.1]
```

**Checkmk Version and Edition**

```console
2.2.0p21
```

**Collection Version**

```console
$ ansible-galaxy collection list
checkmk.general               4.2.0
```

**To Reproduce**
2. Run '....'
3. Execute '....'

**Expected behavior**

Able to create Host and Service groups Rules with an Ansible playbook.

**Actual behavior**

**Minimum reproduction example**

```yaml

```

**Additional context**

 If this is not the correct way/place for Feature Requests, do let me know where I should post it. (first time doing it.)

**Comment by robin-checkmk** [comment]
@atanaskupenov your feature request is a little thin. Do you want to create these rules?
![image](https://github.com/Checkmk/ansible-collection-checkmk.general/assets/93658105/cf5510bf-da87-4bac-93a9-fa3487469420)
Because you can already do that with the `rule` module.

**Comment by atanaskupenov** [comment]
Thanks for the fast reply,  that is what I was looking for.  I'll check tomorrow why I've missed it.

**Comment by robin-checkmk** [comment]
Glad I could help! I am going to go ahead and close this issue, feel free to let me know if the `rule` does not meet your requirements.

**Comment by atanaskupenov** [comment]
After a bit of manual force and lots of trail and error I found out what I had missed. Leaving it here for future reference if someone else needs it : 
    - name: "Create host group Rules for dcs"
      checkmk.general.rule:
        server_url: "{{ checkmk_var_server_url }}"
        site: "{{ checkmk_var_site }}"
        automation_user: "{{ checkmk_var_automation_user }}"
        automation_secret: "{{ checkmk_var_automation_secret }}"
        ruleset: "host_groups"
        rule:
          location:
            folder: "/"
          value_raw: '"{{ item.name }}"'
          conditions: {
            "host_labels": [],
            "service_labels": [],
            "host_tags": [
              {
                "key": "custom_dc",
                "operator": "is",
                "value": "{{ item.name }}"
              }
            ]
          }
          properties: {
            "comment": "{{ ansible_date_time.iso8601 }} - Ansible managed",
            "description": "Create Host Group Rules for dcs",
            "disabled": false
          }
        state: "present"
      run_once: true  # noqa run-once[task]
      delegate_to: localhost
      loop: "{{ checkmk_host_groups }}"
![image](https://github.com/Checkmk/ansible-collection-checkmk.general/assets/132071433/88ab6775-72f6-4e09-97ac-4f6fcc5160ea)
