### ISSUE TITLE
[Feed] folder lookup plugin does not return the title of the folder

### ISSUE THREAD

**Issue by msekania** [Checkmk/ansible-collection-checkmk.general#571]
The current implementation of the folder lookup plugin does not return the `title` of the looked up folder, it only returns  `extensions`

**Describe the bug**

It is rather a feature request!

**Component Name**

Component Name: lookup folder

**Ansible Version**

**Checkmk Version and Edition**

**Collection Version**

**Comment by lgetwan** [comment]
@msekania,
 I fixed that in PR #589. Please check if that fits your needs. Please mind that this is a breaking change, because the structure of the returned data has changed.

**Comment by msekania** [comment]
@lgetwan,

yes, it's fine!
thanks!

**Comment by robin-checkmk** [comment]
Fixed with `5.0.0`.
