### ISSUE TITLE
fixed downtime?

### ISSUE THREAD

**Issue by tbo18** [Checkmk/ansible-collection-checkmk.general#573]
Please verify first that your feedback is not already reported [here](https://github.com/Checkmk/ansible-collection-checkmk.general/issues?q=is%3Aissue+sort%3Aupdated-desc).
If possible and useful provide additional information below. This is optional however.

**Provide your feedback**

Whith this Ansible Module my daily work is significant easyer. But one question pleaase. How is it possibe to create a "fixed" downtime? Alle downtimes that I can create are flexible, but this is not that what I want.

**Component Name**

Component Name: checkmk.general.downtime

**Ansible Version**

```console
$ 2.16.3

```

**Collection Version**

```console
$ ansible-galaxy collection list
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        6.0.0
ansible.posix                            1.5.4
ansible.utils                            3.1.0
ansible.windows                          2.2.0
brocade.fos                              1.3.3
checkmk.general                          4.2.0
community.crypto                         2.17.1
community.docker                         3.7.0
community.general                        8.3.0
community.library_inventory_filtering_v1 1.0.0
community.vmware                         4.1.0
community.windows                        2.1.0
containers.podman                        1.12.0
dellemc.openmanage                       8.7.0
netapp.ontap                             22.9.0

```
**Environment**

CheckMK 2.2.0p22 - Red Hat Enterprise Linux release 8.9 (Ootpa)

**Screenshots**

**Additional context**

**Comment by robin-checkmk** [comment]
Hi @tbo18! Please share your Ansible configuration, at least the task that you use to schedule the downtime and corresponding variables.

**Comment by tbo18** [comment]
Hallo Robin,

***@***.***

***@***.***

Ist das ausreichend?

VG
Thomas Borger
IT-Systemingenieur
Zentralbereich Informationstechnische und allgemeine Dienste
ESG Elektroniksystem- und Logistik-GmbH
Livry-Gargan-Straße 6, 82256 Fürstenfeldbruck
Telefon: +49 89 92161-2737
Telefax: +49 89 9216-16-2737
***@***.***
www.esg.de


ESG ELEKTRONIKSYSTEM- UND LOGISTIK-GMBH

Rechtsform / Legal Form: Gesellschaft mit beschränkter Haftung
Sitz / Registered Office: München
Handelsregister / Commercial Register: Registergericht München, HRB 219422
Vorsitzender des Aufsichtsrats / Chairman of the Supervisory Board: Alexander Schemann
Geschäftsführer / Board of Management: Katja Ziegler, Christoph Otten

Von: Robin Gierse ***@***.***>
Gesendet: Dienstag, 5. März 2024 19:32
An: Checkmk/ansible-collection-checkmk.general ***@***.***>
Cc: Borger Thomas ***@***.***>; Mention ***@***.***>
Betreff: Re: [Checkmk/ansible-collection-checkmk.general] fixed downtime? (Issue #573)

WARNUNG: Diese E-Mail kam von außerhalb der Organisation. Klicken Sie nicht auf Links oder öffnen Sie keine Anhänge, es sei denn, Sie kennen den Absender und wissen, dass der Inhalt sicher ist.


Hi @tbo18<https://github.com/tbo18>! Please share your Ansible configuration, at least the task that you use to schedule the downtime and corresponding variables.

**Comment by robin-checkmk** [comment]
Hi @tbo18, the only information I get from your mail is this:
```
***@***.***

***@***.***
```
I do not even know what that is supposed to be, but I need the YAML definition of the task you use to schedule the downtime.
