### ISSUE TITLE
[FEED] Configure new web services monitoring

### ISSUE THREAD

**Issue by mueller-ma** [Checkmk/ansible-collection-checkmk.general#609]
**Provide your feedback**

CheckMK server 2.3 introduced a new website monitoring. Is it possible to configure this via Ansible? We already have some data about URLs in Ansible (e.g. Apache webserver config) and we'd like to re-use this data for monitoring.

**Comment by Max-checkmk** [comment]
Hi mueller-ma,

i assume that you speak about the "Check HTTP web service" check ?
Like everything in Checkmk, this will be configured with a rule.
So you will be able to configure this with our already existent rule module.

But please be patient until the next major ansible release which will bring compatibility for the Checkmk 2.3 API.

KR,
Max
