### ISSUE TITLE
[BUG] Unable to register agent for automatic updates

### ISSUE THREAD

**Issue by mueller-ma** [Checkmk/ansible-collection-checkmk.general#631]
**Describe the bug**

The PR https://github.com/Checkmk/ansible-collection-checkmk.general/pull/615 introduced an issue where the agent won't get registered on the server.

**Component Name**

Component Name: agent role

**Ansible Version**

```console
$ ansible --version
ansible [core 2.17.1]
```

**Checkmk Version and Edition**

```console
Checkmk Enterprise Edition 2.3.0p3
```

**Collection Version**

```console
$ ansible-galaxy collection list
5.1.0
```

**Expected behavior**

Registration is only skipped, when the agent is registered.

**Actual behavior**

The file `/var/lib/check_mk_agent/cache/plugins_cmk-update-agent.cache` is read and checked if it contains the `server/site`. However this substring may be included in the file, even if the agent is unregistered:

````
# Unregistered agent
# cat /var/lib/check_mk_agent/cache/plugins_cmk-update-agent.cache
<<<cmk_update_agent_status:sep(0)>>>
{"last_check": null, "last_update": null, "aghash": null, "pending_hash": null, "update_url": "<redacted>", "trusted_certs": <redacted>, "error": "The agent updater is not registered at the deployment server"}
````

````
# Registered agent
# cat /var/lib/check_mk_agent/cache/plugins_cmk-update-agent.cache
<<<cmk_update_agent_status:sep(0)>>>
{"last_check": 1719557138.6292932, "last_update": 1717663389.3798563, "aghash": "4c83164da51695b3", "pending_hash": null, "update_url": "<redacted>", "trusted_certs": <redacted>, "error": null}
````

Maybe check if `"error": null` is also in the file and and skip the registration then.

**Comment by robin-checkmk** [comment]
I see and understand the initial error and I split the second comment to a dedicated issue.

As soon as I find the time, I will improve the logic, that checks for existing registration. As I need to align this with Windows as well, it might take a little time. If you want to get started on a PR, I will gladly contribute there.

**Comment by robin-checkmk** [comment]
@mueller-ma I pushed a fix with #636. Can you take a look and maybe even test, if the fix works for you?

**Comment by mueller-ma** [comment]
I can test it when I need to setup the agent the next time, but that may take some time.

**Comment by robin-checkmk** [comment]
The release might have already happened then, but I appreciate it regardless!
