### ISSUE TITLE
[BUG] Integration tests for downtime module creates downtime in the past

### ISSUE THREAD

**Issue by maroessler** [Checkmk/ansible-collection-checkmk.general#633]
**Describe the bug**
During https://github.com/Checkmk/ansible-collection-checkmk.general/pull/632#issuecomment-2203412153 we noticed that the integration tests for the downtime module try to create a downtime in the past which is apparently discarded by Checkmk. This causes the following test that tries to remove this downtime to never find anything to remove. 

**Component Name**
Component Name: checkmk.general.downtime

**Ansible Version**
not applicable

**Checkmk Version and Edition**
not applicable

**Collection Version**
```console
$ ansible-galaxy collection list
checkmk.general                          5.1.0
```

**To Reproduce**
1. Run integration tests for downtime module
2. See error

```
TASK [downtime : 2.3.0p6 - CRE - Delete downtime on host without comment.] *****
ok: [testhost] => (item={'name': 'test1.tld', 'folder': '/'}) => {"ansible_loop_var": "item", "changed": false, "item": {"folder": "/", "name": "test1.tld"}, "msg": "'test1.tld' has no downtimes with comment 'Created by Ansible'."}
ok: [testhost] => (item={'name': 'test2.tld', 'folder': '/'}) => {"ansible_loop_var": "item", "changed": false, "item": {"folder": "/", "name": "test2.tld"}, "msg": "'test2.tld' has no downtimes with comment 'Created by Ansible'."}
ok: [testhost] => (item={'name': 'test3.tld', 'folder': '/'}) => {"ansible_loop_var": "item", "changed": false, "item": {"folder": "/", "name": "test3.tld"}, "msg": "'test3.tld' has no downtimes with comment 'Created by Ansible'."}
ok: [testhost] => (item={'name': 'test4.tld', 'folder': '/'}) => {"ansible_loop_var": "item", "changed": false, "item": {"folder": "/", "name": "test4.tld"}, "msg": "'test4.tld' has no downtimes with comment 'Created by Ansible'."}
ok: [testhost] => (item={'name': 'test5.tld', 'folder': '/'}) => {"ansible_loop_var": "item", "changed": false, "item": {"folder": "/", "name": "test5.tld"}, "msg": "'test5.tld' has no downtimes with comment 'Created by Ansible'."}
```

**Expected behavior**
The mentioned test should report a change and delete the downtime.

**Actual behavior**
Test cannot find downtime and therefore does nothing.

**Minimum reproduction example**
Not applicable

**Comment by robin-checkmk** [comment]
This was also fixed in #632.
