### ISSUE TITLE
[BUG] Agent role crashes, when connections file absent

### ISSUE THREAD

**Issue by robin-checkmk** [Checkmk/ansible-collection-checkmk.general#634]
Also the role crashes when a file doesn't exist:
````
fatal: [<redacted>]: FAILED! => changed=false
  cmd:
  - cat
  - /var/lib/cmk-agent/registered_connections.json
  delta: '0:00:00.006522'
  end: '2024-07-02 16:23:50.121297'
  msg: non-zero return code
  rc: 1
  start: '2024-07-02 16:23:50.114775'
  stderr: 'cat: /var/lib/cmk-agent/registered_connections.json: No such file or directory'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
````

I noticed this issue on Rapberry Pis, so maybe the path is different on arm?

_Originally posted by @mueller-ma in https://github.com/Checkmk/ansible-collection-checkmk.general/issues/631#issuecomment-2203366127_

**Comment by robin-checkmk** [comment]
Curious. The `failed_when` directive should make the task not fail, if the `rc` is `0` or `1`, as the latter means an absent file, which is fine. Let me double-check this.

**Comment by robin-checkmk** [comment]
@mueller-ma I cannot reproduce this issue. For me the `failed_when` logic works just fine. No matter if the file exists or not, the task is fine. Can you double-check on your end? Do you have any non-default Ansible configuration on place?

**Comment by mueller-ma** [comment]
There're two tasks using `cat`, but only one of them catches `failure code == 1`: https://github.com/Checkmk/ansible-collection-checkmk.general/blob/main/roles/agent/tasks/Linux.yml#L90-L103
